 /******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

'use strict';

var express = require('express');
var app = express();
  
app.get('/', function(req, res){
  
  var ip = req.headers['x-forwarded-for'].split(',')[0];
  var language = req.headers['accept-language'].split(',')[0];
  //var software = 
  
  console.log(req.headers['user-agent'])
  res.send(req.headers.host);
})

app.listen(process.env.PORT, function () {
  console.log('Node.js listening ...');
});

